name: CTSE-Microservices-CI/CD-Pipeline

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.KUBERNETES_ID_UNI }}
  GKE_CLUSTER: k8s-order-service-for-it19040172 
  GKE_ZONE: us-central1-c
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Building Project
      run: mvn clean install
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME_UNI }}
        password: ${{ secrets.DOCKER_PASSWORD_UNI }}
    - name: Building Docker Image
      run: docker build . --file Dockerfile --tag it19040172/orderservice:1.2
    - name: Pushing Docker Image to Docker Hub
      run: docker push it19040172/orderservice:1.2
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - id: "auth"
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.KUBERNETES_SA_KEY_UNI }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

# Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Use GCloud CLI
      run: gcloud info

# Get the GKE credentials so we can deploy to the cluster
    - run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

    - name: deploy to kubenets
      run: kubectl apply -f k8s/docker-k8s-order-service.yaml
